# name if the filename -> filename.go
# HELLO WORLD

[[exercises]]
name = "helloworld"
path = "exercises/helloworld/helloworld.go"
mode = "compile"
hint = """ """

# VARIABLES

[[exercises]]
name = "variables1"
path = "exercises/variables/variables1.go"
mode = "compile"
hint = """ """
